### ISSUE TITLE
CSV import fails in 1.2.1

### ISSUE THREAD

**Issue by hsaito** [hsaito/HSLBase#6]
CSV import fails:
Command line used: dotnet HSLProcessor.dll importcsv addition_hsl.csv

2017-06-11 00:59:57,320 [1] DEBUG HSLProcessor.Program - Starting the process.
2017-06-11 00:59:57,340 [1] INFO  HSLProcessor.Importer - Importing a CSV file /home/hideki/Dropbox/workshop/HSLProcessor/addition_hsl.csv
2017-06-11 00:59:57,516 [1] ERROR HSLProcessor.Importer - Failed importing CSV.
2017-06-11 00:59:57,517 [1] DEBUG HSLProcessor.Importer - The given key was not present in the dictionary.
2017-06-11 00:59:57,539 [1] DEBUG HSLProcessor.Importer -    at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at HSLProcessor.Importer.<ImportCsvAsync>d__3.MoveNext() in /home/hideki/Documents/VC/HSLBase/HSLProcessor/Import.cs:line 59
2017-06-11 00:59:57,541 [1] ERROR HSLProcessor.Program - Import failed

**Comment by hsaito** [comment]
Fixed by ef80a320b026de69f508796a6f0f9cfa2b1bcc26
